/**
 * MathFlow AI — Topic Definitions
 * Lists all available math topics grouped by educational level.
 * Ogni voce: { level, topic, icon, graphHint, area, subtypes }
 * - area: macro-area usata dai chip di filtro sopra la griglia
 * - subtypes: tipi di esercizio proposti quando si apre l'argomento
 */

window.TOPICS = [
    // ===== ELEMENTARI =====
    { level: 'Elementari', topic: 'Addizioni e Sottrazioni', icon: '➕', graphHint: 'bar-chart', area: 'Aritmetica',
      subtypes: ['Addizioni in colonna', 'Sottrazioni in colonna', 'Calcolo mentale', 'Problemi con le operazioni'] },
    { level: 'Elementari', topic: 'Moltiplicazioni e Divisioni', icon: '✖️', graphHint: 'bar-chart', area: 'Aritmetica',
      subtypes: ['Moltiplicazioni in colonna', 'Divisioni con resto', 'Tabelline', 'Problemi con le operazioni'] },
    { level: 'Elementari', topic: 'Frazioni', icon: '🍕', graphHint: 'fraction-pie', area: 'Aritmetica',
      subtypes: ['Riconoscere frazioni', 'Frazioni equivalenti', 'Confronto tra frazioni', 'Frazione di una quantità'] },
    { level: 'Elementari', topic: 'Geometria Base', icon: '📐', graphHint: 'geometry', area: 'Geometria',
      subtypes: ['Perimetri', 'Aree', 'Riconoscere le figure', 'Problemi con disegno'] },
    { level: 'Elementari', topic: 'Problemi con le Misure', icon: '📏', graphHint: 'bar-chart', area: 'Aritmetica',
      subtypes: ['Lunghezze', 'Pesi e capacità', 'Tempo e denaro', 'Equivalenze'] },

    // ===== MEDIE =====
    { level: 'Medie', topic: 'Espressioni Aritmetiche', icon: '🧮', graphHint: 'none', area: 'Aritmetica',
      subtypes: ['Con numeri naturali', 'Con frazioni', 'Con potenze', 'Con parentesi annidate'] },
    { level: 'Medie', topic: 'Multipli, Divisori, MCD e mcm', icon: '🧩', graphHint: 'none', area: 'Aritmetica',
      subtypes: ['Criteri di divisibilità', 'Scomposizione in fattori primi', 'Calcolo di MCD e mcm', 'Problemi con MCD e mcm'] },
    { level: 'Medie', topic: 'Potenze e Radici', icon: '🔋', graphHint: 'exponential', area: 'Aritmetica',
      subtypes: ['Proprietà delle potenze', 'Espressioni con potenze', 'Radici quadrate', 'Notazione scientifica'] },
    { level: 'Medie', topic: 'Numeri Relativi', icon: '🔄', graphHint: 'bar-chart', area: 'Aritmetica',
      subtypes: ['Somma algebrica', 'Moltiplicazione e divisione', 'Espressioni con i relativi', 'Problemi con i relativi'] },
    { level: 'Medie', topic: 'Proporzioni e Percentuali', icon: '📊', graphHint: 'bar-chart', area: 'Aritmetica',
      subtypes: ['Proporzioni', 'Percentuali', 'Sconti e aumenti', 'Problemi del tre semplice'] },
    { level: 'Medie', topic: 'Monomi e Polinomi', icon: '🔤', graphHint: 'none', area: 'Algebra',
      subtypes: ['Operazioni con monomi', 'Somma di polinomi', 'Prodotto di polinomi', 'Espressioni letterali'] },
    { level: 'Medie', topic: 'Equazioni di Primo Grado', icon: '🔢', graphHint: 'linear', area: 'Algebra',
      subtypes: ['Equazioni intere', 'Equazioni con frazioni', 'Problemi con equazioni', 'Verifica della soluzione'] },
    { level: 'Medie', topic: 'Geometria Piana', icon: '📏', graphHint: 'geometry', area: 'Geometria',
      subtypes: ['Triangoli', 'Quadrilateri', 'Circonferenza e cerchio', 'Problemi con le aree'] },
    { level: 'Medie', topic: 'Teorema di Pitagora', icon: '🔺', graphHint: 'geometry', area: 'Geometria',
      subtypes: ['Calcolo dell\'ipotenusa', 'Calcolo di un cateto', 'Applicazioni alle figure piane', 'Problemi reali'] },
    { level: 'Medie', topic: 'Geometria Solida', icon: '🧊', graphHint: 'none', area: 'Geometria',
      subtypes: ['Volumi', 'Superfici', 'Prismi e cilindri', 'Problemi con i solidi'] },
    { level: 'Medie', topic: 'Piano Cartesiano', icon: '📍', graphHint: 'linear', area: 'Geometria analitica',
      subtypes: ['Punti e coordinate', 'Distanza tra due punti', 'Punto medio', 'Perimetri e aree nel piano'] },
    { level: 'Medie', topic: 'Statistica e Grafici', icon: '📊', graphHint: 'bar-chart', area: 'Probabilità e statistica',
      subtypes: ['Media, moda e mediana', 'Lettura di grafici', 'Tabelle di frequenza', 'Problemi con dati'] },
    { level: 'Medie', topic: 'Probabilità di Base', icon: '🎲', graphHint: 'bar-chart', area: 'Probabilità e statistica',
      subtypes: ['Probabilità semplice', 'Eventi complementari', 'Probabilità con dadi e carte', 'Problemi di probabilità'] },

    // ===== SUPERIORI (biennio) =====
    { level: 'Superiori', topic: 'Radicali', icon: '√', graphHint: 'none', area: 'Algebra',
      subtypes: ['Semplificazione', 'Operazioni con radicali', 'Razionalizzazione', 'Potenze con esponente frazionario'] },
    { level: 'Superiori', topic: 'Polinomi e Prodotti Notevoli', icon: '🧮', graphHint: 'none', area: 'Algebra',
      subtypes: ['Quadrato di binomio', 'Cubo di binomio', 'Somma per differenza', 'Divisione tra polinomi', 'Regola di Ruffini'] },
    { level: 'Superiori', topic: 'Scomposizione in Fattori', icon: '🧩', graphHint: 'none', area: 'Algebra',
      subtypes: ['Raccoglimento totale e parziale', 'Differenza di quadrati', 'Trinomio speciale', 'Somma e differenza di cubi', 'Scomposizione con Ruffini'] },
    { level: 'Superiori', topic: 'Frazioni Algebriche', icon: '➗', graphHint: 'none', area: 'Algebra',
      subtypes: ['Semplificazione', 'Operazioni', 'Espressioni', 'Condizioni di esistenza'] },
    { level: 'Superiori', topic: 'Equazioni Fratte', icon: '🔣', graphHint: 'none', area: 'Algebra',
      subtypes: ['Di primo grado', 'Di secondo grado', 'Con parametro', 'Problemi con equazioni fratte'] },
    { level: 'Superiori', topic: 'Equazioni di Secondo Grado', icon: '📈', graphHint: 'quadratic', area: 'Algebra',
      subtypes: ['Complete', 'Spurie e pure', 'Con parametro', 'Somma e prodotto delle radici', 'Problemi di secondo grado'] },
    { level: 'Superiori', topic: 'Sistemi di Equazioni', icon: '🔀', graphHint: 'system', area: 'Algebra',
      subtypes: ['Metodo di sostituzione', 'Metodo di riduzione', 'Metodo di Cramer', 'Sistemi fratti', 'Problemi con sistemi'] },
    { level: 'Superiori', topic: 'Disequazioni', icon: '⚖️', graphHint: 'quadratic', area: 'Algebra',
      subtypes: ['Di primo grado', 'Di secondo grado', 'Fratte', 'Di grado superiore'] },
    { level: 'Superiori', topic: 'Sistemi di Disequazioni', icon: '⛓️', graphHint: 'custom', area: 'Algebra',
      subtypes: ['Di primo grado', 'Di secondo grado', 'Fratte', 'Con condizioni di esistenza'] },
    { level: 'Superiori', topic: 'Equazioni e Disequazioni con Valore Assoluto', icon: '|x|', graphHint: 'custom', area: 'Algebra',
      subtypes: ['Equazioni elementari', 'Disequazioni elementari', 'Con due valori assoluti', 'Miste'] },
    { level: 'Superiori', topic: 'Retta nel Piano Cartesiano', icon: '📏', graphHint: 'linear', area: 'Geometria analitica',
      subtypes: ['Equazione della retta', 'Rette parallele e perpendicolari', 'Distanza punto-retta', 'Fasci di rette', 'Problemi con triangoli'] },
    { level: 'Superiori', topic: 'Geometria Euclidea', icon: '📐', graphHint: 'geometry', area: 'Geometria',
      subtypes: ['Criteri di congruenza', 'Teoremi sui triangoli', 'Parallelogrammi', 'Circonferenza e corde', 'Similitudine'] },
    { level: 'Superiori', topic: 'Statistica Descrittiva', icon: '📊', graphHint: 'bar-chart', area: 'Probabilità e statistica',
      subtypes: ['Media, varianza e scarto quadratico', 'Frequenze e istogrammi', 'Mediana e quartili', 'Problemi con dati reali'] },

    // ===== SUPERIORI (triennio) =====
    { level: 'Superiori', topic: 'Parabola', icon: '🌉', graphHint: 'quadratic', area: 'Geometria analitica',
      subtypes: ['Vertice, fuoco e direttrice', 'Parabola per tre punti', 'Rette tangenti', 'Problemi con la parabola'] },
    { level: 'Superiori', topic: 'Circonferenza', icon: '⭕', graphHint: 'geometry', area: 'Geometria analitica',
      subtypes: ['Equazione della circonferenza', 'Centro e raggio', 'Rette tangenti', 'Circonferenza per tre punti'] },
    { level: 'Superiori', topic: 'Ellisse e Iperbole', icon: '🪐', graphHint: 'none', area: 'Geometria analitica',
      subtypes: ['Equazione canonica dell\'ellisse', 'Equazione canonica dell\'iperbole', 'Eccentricità', 'Rette tangenti'] },
    { level: 'Superiori', topic: 'Funzioni e Dominio', icon: 'ƒ', graphHint: 'custom', area: 'Analisi',
      subtypes: ['Dominio di funzioni razionali', 'Dominio con radici', 'Dominio con logaritmi', 'Funzioni pari e dispari', 'Composizione di funzioni'] },
    { level: 'Superiori', topic: 'Funzioni Irrazionali', icon: '√x', graphHint: 'custom', area: 'Analisi',
      subtypes: ['Equazioni irrazionali', 'Disequazioni irrazionali', 'Dominio e segno', 'Grafici con radici'] },
    { level: 'Superiori', topic: 'Goniometria', icon: '🌀', graphHint: 'trigonometric', area: 'Trigonometria',
      subtypes: ['Angoli e radianti', 'Funzioni goniometriche', 'Archi associati', 'Formule di addizione', 'Formule di duplicazione e bisezione'] },
    { level: 'Superiori', topic: 'Equazioni Goniometriche', icon: '〰️', graphHint: 'trigonometric', area: 'Trigonometria',
      subtypes: ['Elementari', 'Riconducibili a elementari', 'Lineari in seno e coseno', 'Omogenee di secondo grado', 'Disequazioni goniometriche'] },
    { level: 'Superiori', topic: 'Equazioni Esponenziali', icon: '🚀', graphHint: 'exponential', area: 'Analisi',
      subtypes: ['Con la stessa base', 'Con sostituzione', 'Disequazioni esponenziali', 'Problemi di crescita e decadimento'] },
    { level: 'Superiori', topic: 'Equazioni Logaritmiche', icon: '📉', graphHint: 'custom', area: 'Analisi',
      subtypes: ['Proprietà dei logaritmi', 'Equazioni logaritmiche', 'Disequazioni logaritmiche', 'Cambio di base'] },
    { level: 'Superiori', topic: 'Limiti', icon: '♾️', graphHint: 'custom', area: 'Analisi',
      subtypes: ['Forme indeterminate', 'Limiti notevoli', 'Limiti con confronto', 'Definizione e verifica'] },
    { level: 'Superiori', topic: 'Continuità e Asintoti', icon: '🛤️', graphHint: 'custom', area: 'Analisi',
      subtypes: ['Asintoti orizzontali e verticali', 'Asintoti obliqui', 'Punti di discontinuità', 'Continuità con parametro'] },
    { level: 'Superiori', topic: 'Studio di Funzione', icon: '🔬', graphHint: 'custom', area: 'Analisi',
      subtypes: ['Razionale fratta', 'Irrazionale', 'Esponenziale', 'Logaritmica', 'Con valore assoluto'] },
    { level: 'Superiori', topic: 'Successioni e Progressioni', icon: '🪜', graphHint: 'custom', area: 'Analisi',
      subtypes: ['Progressioni aritmetiche', 'Progressioni geometriche', 'Limiti di successioni', 'Principio di induzione'] },
    { level: 'Superiori', topic: 'Calcolo Combinatorio', icon: '🃏', graphHint: 'none', area: 'Probabilità e statistica',
      subtypes: ['Permutazioni', 'Disposizioni', 'Combinazioni', 'Binomio di Newton', 'Problemi misti'] },
    { level: 'Superiori', topic: 'Probabilità', icon: '🎲', graphHint: 'bar-chart', area: 'Probabilità e statistica',
      subtypes: ['Probabilità classica', 'Probabilità composta', 'Probabilità condizionata', 'Teorema di Bayes', 'Variabili aleatorie discrete'] },
    { level: 'Superiori', topic: 'Numeri Complessi', icon: 'ℂ', graphHint: 'none', area: 'Algebra',
      subtypes: ['Forma algebrica', 'Forma trigonometrica', 'Potenze e radici', 'Equazioni in campo complesso'] },

    // ===== UNIVERSITÀ =====
    { level: 'Università', topic: 'Derivate', icon: '𝑓\'', graphHint: 'derivative', area: 'Analisi',
      subtypes: ['Derivate fondamentali', 'Regole di derivazione', 'Derivata di funzione composta', 'Retta tangente', 'Problemi di massimo e minimo'] },
    { level: 'Università', topic: 'Integrali', icon: '∫', graphHint: 'integral', area: 'Analisi',
      subtypes: ['Integrali immediati', 'Per sostituzione', 'Per parti', 'Funzioni razionali fratte', 'Integrali definiti e aree'] },
    { level: 'Università', topic: 'Equazioni Differenziali', icon: '📝', graphHint: 'custom', area: 'Analisi',
      subtypes: ['A variabili separabili', 'Lineari del primo ordine', 'Lineari del secondo ordine omogenee', 'Problemi di Cauchy'] },
    { level: 'Università', topic: 'Algebra Lineare', icon: '🔢', graphHint: 'none', area: 'Algebra',
      subtypes: ['Matrici e operazioni', 'Determinanti', 'Sistemi lineari', 'Autovalori e autovettori', 'Spazi vettoriali'] },
    { level: 'Università', topic: 'Serie e Successioni', icon: '∑', graphHint: 'custom', area: 'Analisi',
      subtypes: ['Serie geometriche', 'Criteri di convergenza', 'Serie a segni alterni', 'Serie di potenze'] },
];
